[Definition]

failregex = .*Path=/(wp-admin|wp-login|wordpress|wp-json|phpmyadmin|pma|\.env|\.git|cgi-bin|vendor|login\.php|manager|console|jasperserver|zabbix|owncloud|status\.php|remote|shell|boaform|HNAP1|xmlrpc\.php).*

            .*GET\s+"/(wp-admin|wp-login|wordpress|wp-json|phpmyadmin|pma|\.env|\.git|cgi-bin|vendor|login|remote|boaform|HNAP1|xmlrpc\.php).*".*<HOST>.*

ignoreregex =