[Definition]
failregex = ^\{"log":".*?(?:wp-admin|wp-login|wordpress|wp-json|phpmyadmin|pma|\.env|\.git|cgi-bin|vendor|login|manager|console|jasperserver|zabbix|owncloud|status\.php|remote|shell|boaform|HNAP1|xmlrpc\.php).*?<HOST>.*?"
            ^\{"log":".*?GET\s+\"/(?:wp-admin|wp-login|wordpress|wp-json|phpmyadmin|pma|\.env|\.git|cgi-bin|vendor|login|remote|boaform|HNAP1|xmlrpc\.php).*?\".*?<HOST>.*?"
ignoreregex =
