jobs:
  - name: local
    url: unix:///var/run/docker.sock
    collect_container_size: true
    collect_container_labels: true
    collect_container_network: true
    collect_images_stats: true
    timeout: 2