jobs:
  - name: nofelet-web
    url: https://127.0.0.1:8080/nofelet-web/api/v1/metrics
    tls_skip_verify: yes
  - name: nofelet-chat
    url: https://127.0.0.1:8081/nofelet-chat/api/v1/metrics
    tls_skip_verify: yes
  - name: nofelet-signaling
    url: https://127.0.0.1:8082/nofelet-signaling/api/v1/metrics
    tls_skip_verify: yes