[global]
    update every = 1
    memory mode = dbengine
    history = 86400
    access log = none
    bind to = *

[web]
    mode = static-threaded
    web files owner = root
    web files group = root