[nofelet-tls]

enabled = true
filter = nofelet-tls

backend = systemd

journalmatch = CONTAINER_NAME=nofelet-chat + CONTAINER_NAME=nofelet-signaling + CONTAINER_NAME=nofelet-web

findtime = 5m
maxretry = 10
bantime = 1h

action = iptables-allports