[nofelet-scanners]

enabled = true
filter = nofelet-scanners

backend = systemd

journalmatch = CONTAINER_NAME=nofelet-web + CONTAINER_NAME=nofelet-signaling

findtime = 10m
maxretry = 3

bantime = 24h

action = iptables-allports